# Generated by Django 4.2.5 on 2023-11-05 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_board_invite_code_alter_task_taken_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taken_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
