# Generated by Django 4.2.5 on 2023-11-05 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_taken_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='id_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='api.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.column'),
        ),
    ]
