# Generated by Django 4.2.5 on 2023-11-10 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_column_id_board_alter_task_id_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='member_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
