version: '3.8'

services:
  web-project:
    build: 
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webtasker:/usr/src/webtasker/
    ports:
      - 10000:8000
